### ISSUE TITLE
Can't get it to work anymore

### ISSUE THREAD

**Issue by hipstersmoothie** [SamVerschueren/vscode-linter-xo#55]
It doesn't seem like it is starting up and won't load for me at all

has no tab in output panel

edit: This seems to be an issues with workspaces

**Comment by SamVerschueren** [comment]
@xlc Are you able to take a look? If not, I'll try to find out what's going on. It broke since the latest PR I merged.

**Comment by tusbar** [comment]
If this is fixed, it’d be lovely to get a new release, as the linter is not working at the moment. ❤️

**Comment by SamVerschueren** [comment]
Published a new release `2.3.1`, can you try again?

Thanks for fixing @xlc 🎉 ! Much appreciated.

**Comment by tusbar** [comment]
Just installed 2.3.1, and it doesn’t seem to fix it, no linting at all.

I tried restarting, tailing everything in `~/Library/Application\ Support/Code/logs`, couldn’t see anything related to `xo`.

When running the "Fix all auto-fixable problems" I’m getting the following error: 

```
command 'xo.fix' not found
```

**Comment by kevva** [comment]
@SamVerschueren, I can reproduce this issue. Seems like the dependency issue isn't fixed. I'm getting the following:

```
Activating extension 'samverschueren.linter-xo' failed: Cannot find module 'semver'.
```

**Comment by tusbar** [comment]
The issue is in `.vscodeignore`: 

```
client/node_modules/**
!client/node_modules/vscode-jsonrpc/**
!client/node_modules/vscode-languageclient/**
!client/node_modules/vscode-languageserver-protocol/**
!client/node_modules/vscode-languageserver-types/**
```

**Comment by tusbar** [comment]
@kevva you can manually add semver in `~/.vscode/extensions/samverschueren.linter-xo-2.3.1/client/node_modules` to temporarily fix the issue. :)

**Comment by SamVerschueren** [comment]
Released a new version `2.3.2` which should work. Thanks @tusbar for the fix!
